<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'WP\\McpSchema\\' => array($vendorDir . '/wordpress/php-mcp-schema/src'),
    'WP\\MCP\\' => array($vendorDir . '/wordpress/mcp-adapter/includes'),
    'WPDT\\jlawrence\\eos\\' => array($vendorDir . '/jlawrence/eos/src'),
    'WPDT\\ZipStream\\' => array($vendorDir . '/maennchen/zipstream-php/src'),
    'WPDT\\Psr\\SimpleCache\\' => array($vendorDir . '/psr/simple-cache/src'),
    'WPDT\\Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-factory/src', $vendorDir . '/psr/http-message/src'),
    'WPDT\\Psr\\Http\\Client\\' => array($vendorDir . '/psr/http-client/src'),
    'WPDT\\PhpOffice\\PhpSpreadsheet\\' => array($vendorDir . '/phpoffice/phpspreadsheet/src/PhpSpreadsheet'),
    'WPDT\\PHPSQLParser\\' => array($vendorDir . '/greenlion/php-sql-parser/src/PHPSQLParser'),
    'WPDT\\MyCLabs\\Enum\\' => array($vendorDir . '/myclabs/php-enum/src'),
    'WPDT\\Matrix\\' => array($vendorDir . '/markbaker/matrix/classes/src'),
    'WPDT\\HTMLPurifier\\' => array($vendorDir . '/ezyang/htmlpurifier/library/HTMLPurifier'),
    'WPDT\\Firebase\\JWT\\' => array($vendorDir . '/firebase/php-jwt/src'),
    'WPDT\\Composer\\Pcre\\' => array($vendorDir . '/composer/pcre/src'),
    'WPDT\\Complex\\' => array($vendorDir . '/markbaker/complex/classes/src'),
    'Symfony\\Polyfill\\Mbstring\\' => array($vendorDir . '/symfony/polyfill-mbstring'),
);
