<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    '08925158b6e81bdde1d695de10c1614d' => $vendorDir . '/php-di/php-di/src/functions.php',
);
