<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit1f9cc53bacc683e181acf064e399eb95
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('WPDataTables\Vendor\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \WPDataTables\Vendor\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInit1f9cc53bacc683e181acf064e399eb95', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \WPDataTables\Vendor\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit1f9cc53bacc683e181acf064e399eb95', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\WPDataTables\Vendor\Composer\Autoload\ComposerStaticInit1f9cc53bacc683e181acf064e399eb95::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        $filesToLoad = \WPDataTables\Vendor\Composer\Autoload\ComposerStaticInit1f9cc53bacc683e181acf064e399eb95::$files;
        $requireFile = \Closure::bind(static function ($fileIdentifier, $file) {
            if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
                $GLOBALS['__composer_autoload_files'][$fileIdentifier] = true;

                require $file;
            }
        }, null, null);
        foreach ($filesToLoad as $fileIdentifier => $file) {
            $requireFile($fileIdentifier, $file);
        }

        return $loader;
    }
}
